#!/bin/bash
#
# Meteor scaffolding tool
# with modular design
# based on Meteor Guide
# directory structure
#
# Pál Pintér <pal@palpinter.com>
# 2017
#
# License: MIT
#

CONFIG_DIR=~/.config/meteor-cli
CURRENT_DIR=$PWD

if [ -z $1 ]; then
  echo
  echo "  $(tput setaf 1)ERROR: missing command!$(tput setaf 7)"
  echo
  $CONFIG_DIR/tpl-help
  echo
  exit 0
fi

if [ -z $2 ]; then
  echo
  echo "  $(tput setaf 1)ERROR: missing command argument!$(tput setaf 7)"
  echo
  $CONFIG_DIR/tpl-help
  echo
  exit 0
fi

case "$1" in
  "create")
     $CONFIG_DIR/cmd-create-application $2;;
  "module")
    echo create module;;
  "client-config")
    echo create client config;;
  "client-lib")
    echo create client lib;;
  "client-store")
    echo create client store config;;
  "i18n")
    echo create i18n;;
  "method")
    echo create method;;
  "model")
    echo create model;;
  "route")
    echo create model;;
  "server-config")
    echo create server config;;
  "server-lib")
    echo create server lib;;
  "server-method")
    echo create server method;;
  "publication")
    echo create publication;;
  "component")
    echo create component;;
  *)
    echo
    echo "  $(tput setaf 1)ERROR: unknown command!$(tput setaf 7)"
    echo
    $CONFIG_DIR/tpl-help
    echo;;
esac

exit 0
