#!/bin/bash
#
# Meteor scaffolding tool
# with modular design
# based on Meteor Guide
# directory structure
#
# Pál Pintér <pal@palpinter.com>
# 2017
#
# License: MIT
#

CONFIG_DIR=~/.config/meteor-cli

if [ -z $1 ]; then
  echo
  echo "  $(tput setaf 1)ERROR: missing command!$(tput setaf 7)"
  echo
  $CONFIG_DIR/help
  echo
  exit 0
fi

if [ -z $2 ]; then
  echo
  echo "  $(tput setaf 1)ERROR: missing command argument!$(tput setaf 7)"
  echo
  $CONFIG_DIR/help
  echo
  exit 0
fi

echo $PWD
echo command is: $1
echo Scaffolding started

exit 0
