#!/bin/bash
#
# Helper function convert command parameter
# to camel-case
#
# Pintér Pál <pal@palpinter.com>
# 2017
# License: MIT
#
# Parameters:
#  $1 - string to convert
# 
# Sample: camel-case sample-string => sampleString
#

if [ -z $1 ]; then
  echo
  echo "  $(tput setaf 1)Missing command line parameter!$(tput setaf 7)"
  echo
  echo "  Usage: camel-case sample-string"
  echo
  exit 0
fi

CAPITALIZED=$(echo $1 | sed 's/[^ _-]*/\u&/g' | sed 's/-//g')
CAMEL_CASE=$(echo ${CAPITALIZED:0:1} | tr "[A-Z]" "[a-z]")${CAPITALIZED:1}

echo $CAMEL_CASE

exit 0