#!/bin/bash
#
# Helper function convert command parameter
# to capitalize-case
#
# Pintér Pál <pal@palpinter.com>
# 2017
# License: MIT
#
# Parameters:
#  $1 - string to convert
# 
# Sample: capitalize-case sample-string => SampleString
#

if [ -z $1 ]; then
  echo
  echo "  $(tput setaf 1)Missing command line parameter!$(tput setaf 7)"
  echo
  echo "  Usage: capitalze-case sample-string"
  echo
  exit 0
fi

CAPITALIZE_CASE=$(echo $1 | sed 's/[^ _-]*/\u&/g' | sed 's/-//g')

echo $CAPITALIZE_CASE

exit 0