#!/bin/bash
#
# Initial application directory structure add to application
#
# Pintér Pál <pal@palpinter.com>
# 2017
# License: MIT
#

echo client
echo client/config
echo client/lib
echo client/store
echo i18n
echo method
echo model
echo route
echo server
echo server/config
echo server/lib
echo server/publication

exit 0
