#!/bin/bash
#
# Initial application directory structure add to application
#
# Pintér Pál <pal@palpinter.com>
# 2017
# License: MIT
#

echo client
echo client/compatibility
echo client/css
echo imports
echo imports/api
echo imports/startup
echo imports/startup/client
echo imports/startup/server
echo imports/ui
echo imports/ui/component
echo imports/ui/layout
echo imports/ui/page
echo imports/ui/styles
echo private
echo public
echo server

exit 0
