#!/bin/bash
#
# Create application command
#
# Pintér Pál <pal@palpinter.com>
# 2017
# License: MIT
#
# Parameters:
#  $1 - application name
# Sample: cmd-create-application sample-application
#

if [ -z $1 ]; then
  echo
  echo "  $(tput setaf 1)ERROR: missing command argument!$(tput setaf 7)"
  echo
  $CONFIG_DIR/tpl-help
  echo
  exit 0
fi

CONFIG_DIR=~/.config/meteor-cli
ATMOSPHERE_PACKAGES=$($CONFIG_DIR/cfg-atmosphere-packages)
NODE_PACKAGES=$($CONFIG_DIR/cfg-node-packages)
DIR_STRUCTURE=$($CONFIG_DIR/cfg-application-skeleton)

meteor create --bare $1
cd $1
yarn

if [[ ! -z $ATMOSPHERE_PACKAGES ]]; then
  meteor add $ATMOSPHERE_PACKAGES
fi

if [[ ! -z $NODE_PACKAGES ]]; then
  yarn add $NODE_PACKAGES
fi

if [[ ! -z $DIR_STRUCTURE ]]; then
  for DIR in $DIR_STRUCTURE
  do
    mkdir $DIR
    touch $DIR/.gitkeep
  done
  $($CONFIG_DIR/tpl-client-head $1)
  $($CONFIG_DIR/tpl-client-main-coffee)
  $($CONFIG_DIR/tpl-client-main-styl)
  $($CONFIG_DIR/tpl-imports-startup-client-index-coffee)
  $($CONFIG_DIR/tpl-imports-startup-client-index-styl)
  $($CONFIG_DIR/tpl-server-main-coffee)
  $($CONFIG_DIR/tpl-imports-startup-server-index-coffee)
fi

git init
echo node_modules > .gitignore
git add -A
git commit -am 'Initial release'

exit 0