#!/bin/bash
#
# Helper function convert command parameter
# to snake-case
#
# Pintér Pál <pal@palpinter.com>
# 2017
# License: MIT
#
# Parameters:
#  $1 - string to convert
# 
# Sample: snake-case sample-string => sample_string
#

if [ -z $1 ]; then
  echo
  echo "  $(tput setaf 1)Missing command line parameter!$(tput setaf 7)"
  echo
  echo "  Usage: snake-case sample-string"
  echo
  exit 0
fi

SNAKE_CASE=$(echo $1 | sed 's/-/_/g')

echo $SNAKE_CASE

exit 0