#!/bin/bash
#
# Server startup template
#
# Pintér Pál <pal@palpinter.com>
# 2017
# License: MIT
#
# Usage: tpl-imports-startup-server-index-coffee
#

CONFIG_DIR=~/.config/meteor-cli

$CONFIG_DIR/tpl-header imports/startup/server/index.coffee > imports/startup/server/index.coffee

exit 0
