#!/bin/bash
#
# File header template
#
# Pintér Pál <pal@palpinter.com>
# 2017
# License: MIT
#
# Parameters:
#  $1 - file path
# 
# Sample: header /sample/path/to/file
#

if [ -z $1 ]; then
  echo
  echo "  $(tput setaf 1)Missing command line parameter!$(tput setaf 7)"
  echo
  echo "  Usage: header /sample/path/to/file"
  echo
  exit 0
fi

echo "###"
echo "  $1"
echo "###"
echo 
echo "DEBUG = true"
echo "console.log '"$1" is loaded' if DEBUG"
echo ""

exit 0
